// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartCity.TrafficLightController.Data;

#nullable disable

namespace SmartCity.TrafficLightController.Data.Migrations
{
    [DbContext(typeof(TrafficDbContext))]
    partial class TrafficDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartCity.TrafficLightController.Data.Entities.Intersection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentColor")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("RED");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("EmergencyLockUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastChangeReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Normal");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("LastUpdatedAt");

                    b.HasIndex("Mode");

                    b.ToTable("intersections", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-101",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-102",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-103",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-104",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-105",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-106",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-107",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-108",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-109",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-110",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-111",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-112",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-113",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-114",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-115",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-116",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-117",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-118",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-119",
                            RowVersion = 0u
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentColor = "RED",
                            Direction = "Northbound",
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Mode = "Normal",
                            Name = "Intersection-120",
                            RowVersion = 0u
                        });
                });

            modelBuilder.Entity("SmartCity.TrafficLightController.Data.Entities.StateChangeLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("IntersectionId")
                        .HasColumnType("integer");

                    b.Property<double>("LatencyMs")
                        .HasColumnType("double precision");

                    b.Property<string>("NewColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreviousColor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WasEmergency")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("IntersectionId", "ChangedAt");

                    b.ToTable("state_change_logs", (string)null);
                });

            modelBuilder.Entity("SmartCity.TrafficLightController.Data.Entities.StateChangeLog", b =>
                {
                    b.HasOne("SmartCity.TrafficLightController.Data.Entities.Intersection", "Intersection")
                        .WithMany()
                        .HasForeignKey("IntersectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intersection");
                });
#pragma warning restore 612, 618
        }
    }
}
